version: 2.1

orbs:
    heroku: circleci/heroku@1.2.6 # Use the Heroku orb in your config

workflows:
    heroku_deploy:
    jobs:
        - checkout
        - build
        - heroku/deploy-via-git:vhi
            auth:
              user
            requires:
            - build # only run deploy-via-git job if the build job has completed
            filters:
            branches:
                only: master # only run deploy-via-git job on main branch
